apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: myapp-pod
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
    env:
      - name: APP_COLOR
        value: pink
        # valueFrom: configMapRef: conf_ref_1
        # valueFrom: secretKeyRef: secret_ref_1

    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}