apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: myapp-pod
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
      - name: APP_COLOR
        value: pink
        # valueFrom: configMapRef: conf_ref_1
        # valueFrom: secretKeyRef: secret_ref_1

    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}